# Site settings
title: MEDIVIEWSOFT
header-img: img/home-bg.jpg
email: haeeun1231@gmail.com
copyright_name: MEDIVIEWSOFT
description: "MEDIVIEWSOFT"
baseurl: ""
url: "http://www.mediviewsoft.com"
twitter_username: 
github_username:  mediviewsoft
facebook_username:  
email_username:  haeeun1231@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
